# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-03 01:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.IntegerField(default=0, verbose_name='资历')),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('utime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '教练',
                'verbose_name': '教练',
                'db_table': 'coach',
            },
        ),
        migrations.CreateModel(
            name='CoachMemberRef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Coach')),
            ],
            options={
                'verbose_name_plural': '学员教练关联',
                'verbose_name': '学员教练关联',
                'db_table': 'member_coach',
            },
        ),
        migrations.CreateModel(
            name='Figure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('figure', models.ImageField(upload_to='account/figure', verbose_name='形象照')),
                ('desc', models.CharField(blank=True, max_length=200, verbose_name='描述')),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('utime', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '用户形象',
                'verbose_name': '用户形象',
                'db_table': 'user_figure',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('utime', models.DateTimeField(auto_now=True)),
                ('coach', models.ManyToManyField(blank=True, through='account.CoachMemberRef', to='account.Coach')),
                ('gym', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gym.Gymnasium')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '学员',
                'verbose_name': '学员',
                'db_table': 'member',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, db_index=True, max_length=36, verbose_name='昵称')),
                ('intro', models.CharField(blank=True, default='', max_length=500, verbose_name='个性签名')),
                ('phone', models.CharField(blank=True, max_length=16, unique=True, verbose_name='手机号')),
                ('weight', models.IntegerField(default=0, help_text='单位为千克', verbose_name='体重')),
                ('height', models.IntegerField(default=0, help_text='单位为厘米', verbose_name='身高')),
                ('gender', models.SmallIntegerField(choices=[(0, '未知'), (1, '男性'), (2, '女性')], default=0, verbose_name='性别')),
                ('age', models.IntegerField(default=0, verbose_name='年龄')),
                ('u_type', models.SmallIntegerField(choices=[(0, '学员'), (1, '教练')], default=1, verbose_name='用户身份')),
                ('score', models.IntegerField(default=0, verbose_name='积分')),
                ('portrait', models.ImageField(blank=True, upload_to='account/portrait', verbose_name='头像')),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('utime', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '用户信息',
                'verbose_name': '用户信息',
                'db_table': 'user_profile',
            },
        ),
        migrations.CreateModel(
            name='UserRelationConfirm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_type', models.CharField(choices=[('add_member', '添加学员'), ('add_coach', '添加教练'), ('add_friend', '添加好友'), ('add_follow', '添加关注')], max_length=16, verbose_name='关联类型')),
                ('status', models.SmallIntegerField(default=0, verbose_name='状态')),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('utime', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '用户关系绑定',
                'ordering': ('-id',),
                'verbose_name': '用户关系绑定',
                'db_table': 'user_ref_confirm',
            },
        ),
        migrations.CreateModel(
            name='WechatInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unionid', models.CharField(blank=True, help_text='多帐户绑定同一微信开放平台后,会有这个值', max_length=100, verbose_name='开放平台唯一ID')),
                ('openid', models.CharField(max_length=100, unique=True, verbose_name='微信openid')),
                ('headimgurl', models.CharField(blank=True, max_length=500, verbose_name='头像')),
                ('device', models.CharField(blank=True, max_length=100, verbose_name='设备ID')),
                ('apple_id', models.CharField(blank=True, max_length=100, verbose_name='苹果帐户id')),
                ('os_platform', models.SmallIntegerField(choices=[(0, 'iOS'), (1, 'Android'), (2, 'unknown'), (3, 'iOS7')], default=2, verbose_name='系统平台')),
                ('nickname', models.CharField(blank=True, max_length=100, verbose_name='微信昵称')),
                ('sex', models.SmallIntegerField(choices=[(0, '未知'), (1, '男性'), (2, '女性')], default=0, verbose_name='性别')),
                ('city', models.CharField(blank=True, max_length=16, verbose_name='城市名')),
                ('province', models.CharField(blank=True, max_length=16, verbose_name='省名')),
                ('country', models.CharField(blank=True, max_length=16, verbose_name='国家')),
                ('wechat_subscribed', models.BooleanField(default=True, verbose_name='微信关注')),
                ('subscribe_time', models.CharField(blank=True, help_text='值为unix时间截', max_length=16, verbose_name='关注时间')),
                ('groupid', models.SmallIntegerField(default=0, verbose_name='微信分组')),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('utime', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '用户微信信息',
                'verbose_name': '用户微信信息',
                'db_table': 'wechat_info',
            },
        ),
        migrations.AddField(
            model_name='coachmemberref',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Member'),
        ),
    ]
