# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-03 01:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fitness', '0001_initial'),
        ('account', '0001_initial'),
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='expert_tags',
            field=models.ManyToManyField(to='fitness.ExpertTag'),
        ),
        migrations.AddField(
            model_name='coach',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gym.Gymnasium'),
        ),
        migrations.AddField(
            model_name='coach',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='coachmemberref',
            unique_together=set([('member', 'coach')]),
        ),
    ]
