# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-10 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20161103_0100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userrelationconfirm',
            options={'ordering': ('-id',), 'verbose_name': '用户关联请求', 'verbose_name_plural': '用户关联请求'},
        ),
        migrations.RemoveField(
            model_name='wechatinfo',
            name='apple_id',
        ),
        migrations.RemoveField(
            model_name='wechatinfo',
            name='device',
        ),
        migrations.AlterField(
            model_name='wechatinfo',
            name='wechat_subscribed',
            field=models.BooleanField(default=False, verbose_name='微信关注'),
        ),
    ]
