# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-09 11:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20161123_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='gym',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='gym.Gymnasium'),
            preserve_default=False,
        ),
    ]
