# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-12 18:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20161209_1129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='figure',
            options={'ordering': ('-id',), 'verbose_name': '用户形象', 'verbose_name_plural': '用户形象'},
        ),
        migrations.AddField(
            model_name='figure',
            name='cdate',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 12, 12, 18, 13, 29, 452074), verbose_name='日期'),
            preserve_default=False,
        ),
    ]
