# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-03 01:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fitness', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciserecord',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Event'),
        ),
        migrations.AddField(
            model_name='exerciserecord',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.FitnessExercise'),
        ),
        migrations.AddField(
            model_name='exerciserecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exercisemuscle',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.FitnessExercise'),
        ),
        migrations.AddField(
            model_name='exercisemuscle',
            name='muscle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.Muscle'),
        ),
        migrations.AddField(
            model_name='exercisecategory',
            name='user',
            field=models.ForeignKey(blank=True, help_text='用户自定义, 默认对其他人不可见', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='fitgoal',
            unique_together=set([('user', 'name')]),
        ),
        migrations.AlterIndexTogether(
            name='exerciserecord',
            index_together=set([('user', 'event')]),
        ),
    ]
