# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-12 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0003_auto_20161117_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessexercise',
            name='pinyin',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='拼音名称'),
        ),
        migrations.AlterField(
            model_name='fitnessexercise',
            name='name',
            field=models.CharField(db_index=True, max_length=50, verbose_name='名称'),
        ),
    ]
