# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-08 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0004_auto_20161212_1414'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fitnessexercise',
            options={'ordering': ('pinyin',), 'verbose_name': '健身动作', 'verbose_name_plural': '健身动作'},
        ),
        migrations.AddField(
            model_name='goalrecord',
            name='figure',
            field=models.ImageField(blank=True, upload_to='fitness/figure', verbose_name='晒图'),
        ),
    ]
