# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-09 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0005_auto_20170108_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitgoal',
            name='initial',
            field=models.IntegerField(default=0, verbose_name='初始值'),
        ),
        migrations.AddField(
            model_name='fitgoal',
            name='schedule',
            field=models.IntegerField(default=0, help_text='按天数计', verbose_name='达成预期天数'),
        ),
    ]
