# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-23 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20161117_1547'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('-start',), 'verbose_name': 'event', 'verbose_name_plural': 'events'},
        ),
        migrations.AlterField(
            model_name='event',
            name='state',
            field=models.SmallIntegerField(choices=[(-1, '失效'), (0, '待上课'), (1, '已结课'), (2, '预约')], default=0, verbose_name='课程状态'),
        ),
    ]
