# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-07 19:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
        ('schedule', '0003_auto_20161123_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasecourse',
            name='gym',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='gym.Gymnasium'),
            preserve_default=False,
        ),
    ]
