# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-12 12:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_auto_20161208_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='coach',
            field=models.ForeignKey(blank=True, default=10008, help_text='As coach', on_delete=django.db.models.deletion.CASCADE, related_name='coach_user', to=settings.AUTH_USER_MODEL, verbose_name='coach'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='state',
            field=models.SmallIntegerField(choices=[(-1, '休息'), (0, '上课'), (1, '结课'), (2, '预约')], default=0, verbose_name='课程状态'),
        ),
        migrations.AlterField(
            model_name='event',
            name='user',
            field=models.ForeignKey(blank=True, default=10064, help_text='As member', on_delete=django.db.models.deletion.CASCADE, related_name='member_user', to=settings.AUTH_USER_MODEL, verbose_name='user'),
            preserve_default=False,
        ),
    ]
