# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-12 19:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_auto_20161212_1239'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='event',
            index_together=set([('coach', 'start', 'end'), ('coach', 'start', 'end', 'calendar')]),
        ),
    ]
