# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-03 01:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('code', models.CharField(help_text='省级行政区划代码 See  http://www.stats.gov.cn/tjsj/tjbz/xzqhdm/201504/t20150415_712722.html', max_length=6, primary_key=True, serialize=False, verbose_name='城市代号')),
                ('name', models.CharField(max_length=50, verbose_name='行政区名称')),
                ('suffix', models.CharField(max_length=8, verbose_name='行政单位')),
                ('fullname', models.CharField(max_length=16, verbose_name='全名')),
                ('pinyin', models.CharField(max_length=32, verbose_name='拼音')),
                ('py', models.CharField(help_text='列pinyin的简拼序列。如beijing:bj', max_length=4, verbose_name='简拼')),
            ],
            options={
                'verbose_name_plural': '城市列表',
                'verbose_name': '城市列表',
                'db_table': 'c_cities',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(help_text='省级行政区划代码 See  http://www.stats.gov.cn/tjsj/tjbz/xzqhdm/201504/t20150415_712722.html', max_length=6, primary_key=True, serialize=False, verbose_name='国家代号')),
                ('name', models.CharField(max_length=50, null=True)),
                ('languages', models.CharField(blank=True, max_length=250, null=True)),
                ('capital', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': '国家',
                'verbose_name': '国家',
                'db_table': 'c_country',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('code', models.CharField(help_text='省级行政区划代码 See  http://www.stats.gov.cn/tjsj/tjbz/xzqhdm/201504/t20150415_712722.html', max_length=6, primary_key=True, serialize=False, verbose_name='城市代号')),
                ('name', models.CharField(max_length=50, verbose_name='行政区名称')),
                ('suffix', models.CharField(max_length=8, verbose_name='行政单位')),
                ('fullname', models.CharField(max_length=16, verbose_name='全名')),
                ('pinyin', models.CharField(max_length=32, verbose_name='拼音')),
                ('py', models.CharField(help_text='列pinyin的简拼序列。如beijing:bj', max_length=4, verbose_name='简拼')),
                ('pcode', models.ForeignKey(db_column='pcode', on_delete=django.db.models.deletion.CASCADE, to='gym.City')),
            ],
            options={
                'verbose_name_plural': '城区信息',
                'verbose_name': '城区信息',
                'db_table': 'c_district',
            },
        ),
        migrations.CreateModel(
            name='Gymnasium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('score', models.IntegerField(default=0, verbose_name='评分')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='具体位置')),
                ('telephone', models.CharField(blank=True, help_text='多个手机号以,号间隔', max_length=100, verbose_name='联系电话')),
                ('lat', models.FloatField(default=0, verbose_name='纬度')),
                ('lng', models.FloatField(default=0, verbose_name='经度')),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('utime', models.DateTimeField(auto_now=True)),
                ('city_code', models.ForeignKey(blank=True, db_column='city_code', on_delete=django.db.models.deletion.CASCADE, to='gym.City')),
                ('district_code', models.ForeignKey(blank=True, db_column='district_code', on_delete=django.db.models.deletion.CASCADE, to='gym.District')),
            ],
            options={
                'verbose_name_plural': '健身房',
                'verbose_name': '健身房',
                'db_table': 'c_gymnasium',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('code', models.CharField(help_text='省级行政区划代码 See  http://www.stats.gov.cn/tjsj/tjbz/xzqhdm/201504/t20150415_712722.html', max_length=6, primary_key=True, serialize=False, verbose_name='省代号')),
                ('name', models.CharField(max_length=50, verbose_name='行政区名称')),
                ('suffix', models.CharField(max_length=8, verbose_name='行政单位')),
                ('fullname', models.CharField(max_length=16, verbose_name='全名')),
                ('pinyin', models.CharField(max_length=32, verbose_name='拼音')),
                ('py', models.CharField(help_text='列pinyin的简拼序列。如beijing:bj', max_length=4, verbose_name='简拼')),
                ('pcode', models.ForeignKey(db_column='pcode', on_delete=django.db.models.deletion.CASCADE, to='gym.Country')),
            ],
            options={
                'verbose_name_plural': '省列表',
                'verbose_name': '省列表',
                'db_table': 'c_province',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='pcode',
            field=models.ForeignKey(db_column='pcode', on_delete=django.db.models.deletion.CASCADE, to='gym.Province'),
        ),
    ]
