# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-08 18:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gymnasium',
            unique_together=set([('city_code', 'district_code', 'name')]),
        ),
    ]
