# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-03 01:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(0, '通知'), (1, '私信'), (2, '评论'), (3, '@我')], default=0, verbose_name='推送类型')),
                ('target', models.CharField(default='html', help_text='空为不跳转, html为跳网页, app为跳转数据页', max_length=500, verbose_name='跳转类型')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='标题')),
                ('description', models.TextField(blank=True, null=True)),
                ('action_object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('show_time', models.DateTimeField(db_index=True, verbose_name='展示时间')),
                ('unread', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False)),
                ('notified', models.BooleanField(default=False)),
                ('data', jsonfield.fields.JSONField(blank=True, help_text="定制信息, 默认为空; 网页跳转写 {'target_url': ''}", null=True)),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('utime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('action_object_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notify_action_object', to='contenttypes.ContentType')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_notify', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_notify', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '站内信通知',
                'ordering': ('-ctime',),
                'verbose_name': '站内信通知',
            },
        ),
    ]
